/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-linen": "#F5F3EE",
        "on-tertiary-fixed-variant": "#005323",
        "on-surface": "#1b1c1a",
        "surface-container-high": "#eae8e4",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#00210a",
        "on-surface-variant": "#45464d",
        "border-subtle": "#F0EDE6",
        "surface": "#fbf9f5",
        "surface-cream": "#FAF8F5",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-low": "#f5f3ef",
        "surface-bright": "#fbf9f5",
        "on-secondary-fixed-variant": "#6e3900",
        "secondary": "#904d00",
        "secondary-fixed-dim": "#ffb77d",
        "secondary-container": "#fe932c",
        "on-secondary-fixed": "#2f1500",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00210a",
        "inverse-surface": "#30312e",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e2de",
        "primary-fixed-dim": "#bec6e0",
        "surface-container": "#efeeea",
        "surface-variant": "#e4e2de",
        "tertiary-fixed-dim": "#79db8d",
        "surface-dim": "#dbdad6",
        "on-primary-fixed": "#131b2e",
        "on-background": "#1b1c1a",
        "amber-hover": "#B45309",
        "on-primary-container": "#7c839b",
        "background": "#fbf9f5",
        "on-tertiary-container": "#339650",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed": "#95f8a7",
        "inverse-primary": "#bec6e0",
        "tertiary": "#000000",
        "border-warm": "#E8E4DC",
        "outline": "#76777d",
        "primary": {
          DEFAULT: "#0284c7",
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
        "accent": {
          DEFAULT: "#0284c7",
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          600: "#0284c7",
        },
        "primary-container": "#131b2e",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "slate-muted": "#475569",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f0ed",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#ffdcc3",
        "on-secondary-container": "#663500"
      },
      "borderRadius": {
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2.5rem"
      },
      "fontFamily": {
        "sans": ["Noto Sans TC", "Noto Sans", "sans-serif"],
        "body": ["Noto Sans TC", "Noto Sans", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "Noto Sans TC", "sans-serif"],
        "display": ["Plus Jakarta Sans", "Noto Sans TC", "sans-serif"]
      }
    },
  },
  plugins: [],
}
